[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow",
    "validates_models: marks tests as one which validates service models",
]

[tool.isort]
profile = "black"
line_length = 79
honor_noqa = true
src_paths = ["botocore", "tests"]

[tool.black]
line-length = 79
skip_string_normalization = true
